server:
  port: 8081
spring:
  application:
    name: job
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://106.55.198.193:3306/pass?serverTimezone=UTC
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  tokenSessionCheckLogin: false